### ISSUE TITLE
Spawn

### ISSUE THREAD

**Issue by samennis1** [ImmaFreedom-Dev/ImmaFreedomMod#122]
Hello,

I believe /setworldspawn should be blocked (I believe /setspawn already is) As it is very related to /setspawn and has been used by a few users I've seen. From my last post (Blocked /holo for supers only, as well as /setspawn. < that was by Pinch) So I just thought I'd made this because if you blocked /setspawn you should block /setworld spawn, If /setspawn isn't blocked, That's fine, Then you can close this.

Thanks,
Sam

**Comment by OutOfYourMind** [comment]
Accepted :P

**Comment by samennis1** [comment]
xD, Thanks

**Comment by aggelosQQ** [comment]
I'm always using /setspawnworld along with /setspawn. Unblock it please.

**Comment by LegendIsAwesomes** [comment]
Super admins still have access to the command
@aggelosQQ

**Comment by aggelosQQ** [comment]
And what's wrong with it?

**Comment by LegendIsAwesomes** [comment]
They can set the spawn of other players including admins to the void etc

@aggelosqq

**Comment by aggelosQQ** [comment]
I think you are talking about /spawnpoint, /setspawnworld just sets the spawn of the world, if you really want to block it, limit it to admins.

**Comment by DUFCLiam** [comment]
Agreed, Above ^
