### ISSUE TITLE
SeniorAdminWorld - Just wanted to see what my devs and aggelos thinks of this.

### ISSUE THREAD

**Issue by OutOfYourMind** [ImmaFreedom-Dev/ImmaFreedomMod#13]
The title says it all. I'll create it if you two vote yes.

**Comment by LegendIsAwesomes** [comment]
What's the difference between this and adminworld. It'd be no difference.

**Comment by LegendIsAwesomes** [comment]
@outofyourmind

**Comment by OutOfYourMind** [comment]
Well, it is a world for seniors only, I just thought it would be a good incentive for being a senior.

**Comment by aggelosQQ** [comment]
I don't know, if it doesn't take enough space I don't see any problem.

**Comment by OutOfYourMind** [comment]
Accepted then. Will be added on 3.0

**Comment by aggelosQQ** [comment]
Bump @ImmaFreedom-Dev/owners

**Comment by tylerhyperHD** [comment]
Senior admin world? Why don't you just use regular admin world? + not enough space to add = closed
