### ISSUE TITLE
/rules 

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#17]
May I ask why whenever I do /rules in-game, instead of showing the rules that are from the essentials file, rules.txt it shows:
:rules
:Go to http://immafreedom.eu/ for the rules.

I want it to show the message I added on the Essentials folder so the player won't have to go to the website to view them.

This is the message I want:

&6* &2You may view all the rules on: &9"immafreedom.eu/showthread.php?tid=46"&6!
&2Here you can view the main server rules.
&6* &2You may not grief.
&6* &2You may not login on the server with a username that is an administrator on ImmaFreedom.
&6* &2Trolling is not allowed (Death/Troll potions included!)
&6* &2Teleporting others to you without permission is also not allowed.
&6* &2You may not send DDoS/DoX/DoS threats!
&6* &2You may not crash. 

&2These are ImmaFreedom's main rules. &4Do not ignore!

@ImmaFreedom-Dev/member @ImmaFreedom-Dev/owners

**Comment by LegendIsAwesomes** [comment]
Do you want a new cmd completely?

**Comment by OutOfYourMind** [comment]
Will be added, I'll add it.

**Comment by tylerhyperHD** [comment]
This is an essentials issue since I re-did essentials, yet I don't have access to that lol.

**Comment by aggelosQQ** [comment]
Don't have access to what, @tylerhyperHD

**Comment by aggelosQQ** [comment]
I have replaced the command with a plugin.
It works perfectly now.
