### ISSUE TITLE
/uall & /dtoggle

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#22]
TF used to have this command back when they had disguisecraft. 

/Uall disguises all the online players

/dtoggle enables/disables the plugin.

The plugin we use right now is LibDisguise; can we have that command?
@ImmaFreedom-Dev/leaders @ImmaFreedom-Dev/member

**Comment by OutOfYourMind** [comment]
Will add.

**Comment by aggelosQQ** [comment]
@tylerhyperHD, we don't use DisguiseCraft; we are using LibDisguises

**Comment by tylerhyperHD** [comment]
LibDisguises is incompatible with TFM, making this command a useless sort of deal. It's either DisguiseCraft or nothing.
