### ISSUE TITLE
/smite telnet errors

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#23]
01.11 13:51:34 [Server] INFO tylerhyperHD issued server command: /smite Cartman357mag
01.11 13:51:34 [Server] INFO [PREPROCESS_COMMAND] tylerhyperHD(tylerhyperHD): /smite Cartman357mag
01.11 13:51:34 [Server] INFO [PLAYER_COMMAND] tylerhyperHD (tylerhyperHD): /smite Cartman357mag
01.11 13:51:34 [Server] INFO Cartman357mag has been a naughty, naughty boy.
01.11 13:51:34 [Server] ERROR Could not pass event PlayerDeathEvent to stServerMessages v1.5.3
01.11 13:51:34 [Server] INFO org.bukkit.event.EventException
01.11 13:51:34 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:417) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:87) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at me.StevenLawson.TotalFreedomMod.Commands.Command_smite.smite(Command_smite.java:63) [ImmaFreedomMod.jar:?]
01.11 13:51:34 [Server] INFO at me.StevenLawson.TotalFreedomMod.Commands.Command_smite.run(Command_smite.java:32) [ImmaFreedomMod.jar:?]
01.11 13:51:34 [Server] INFO at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandHandler.handleCommand(TFM_CommandHandler.java:70) [ImmaFreedomMod.jar:?]
01.11 13:51:34 [Server] INFO at me.StevenLawson.TotalFreedomMod.TotalFreedomMod.onCommand(TotalFreedomMod.java:228) [ImmaFreedomMod.jar:?]
01.11 13:51:34 [Server] INFO at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandLoader$TFM_DynamicCommand.execute(TFM_CommandLoader.java:307) [ImmaFreedomMod.jar:?]
01.11 13:51:34 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
01.11 13:51:34 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
01.11 13:51:34 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:34 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-12698ea]
01.11 13:51:36 [Multicraft] Skipped 12 lines due to rate limit (30/s)

**Comment by tylerhyperHD** [comment]
stServerMessages is causing that.

**Comment by aggelosQQ** [comment]
Okay; I won't remove this plugin anyway.

**Comment by tylerhyperHD** [comment]
Fixed with a little bit of sauces.
