### ISSUE TITLE
/ulist | /ulist -a

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#25]
/ulist - This command will show all the online disguised players.

/ulist -a - This command will show players that are near you.

**Comment by OxLemonxO** [comment]
I can do this if we use LIbsDisguises instead of DisguiseCraft

**Comment by aggelosQQ** [comment]
@OxLemonxO I prefer disguisecraft because it has less disguises when libdisguises has many and most of them can harm the server.

**Comment by OxLemonxO** [comment]
@aggelosQQ Which ones can harm the server?

**Comment by OutOfYourMind** [comment]
I agree with @OxLemonxO, LibsDisguises will be added. That is final.

**Comment by tylerhyperHD** [comment]
LibDisguises has protocols in it that can potentially harm the server, that is why I use DisguiseCraft. If you can fix these issues, then I will reconsider adding it.

**Comment by OxLemonxO** [comment]
I think your talking about ProtocolLib? if not, what protocols are you talking about?

**Comment by aggelosQQ** [comment]
No, I don't really like LibDisguises. I prefer the old, good one.

**Comment by tylerhyperHD** [comment]
I am talking about the protocols that left TotalFreedom laggy for months.

**Comment by tylerhyperHD** [comment]
Denied anyways.

**Comment by aggelosQQ** [comment]
Ummm, what is denied? /ulist? You already added it.

**Comment by tylerhyperHD** [comment]
Stupid me lol
