### ISSUE TITLE
I don't know if it is possible - it is just a thought - Vote Reward

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#26]
To make people vote for the server, I thought of a rank called Voter, which gets some commands and other features (we will think of them if we accept this idea) and this rank will be given to the top 3 voters of Minecraft-MP every month. The rank duration will be one month. 

What do you think? It sounds hard to implement but I think it will help us get more players if they vote for this rank?
@ImmaFreedom-Dev/member

**Comment by tylerhyperHD** [comment]
that would be hard yet it would take time.

**Comment by aggelosQQ** [comment]
Yes, obviously, however, if any of you is willing to spend the required time to implement this, it would be great.

**Comment by LegendIsAwesomes** [comment]
I have an idea how to do this though I'm suspended @aggelosqa

**Comment by aggelosQQ** [comment]
You can still contribute by making pull requests, @LegendIsAwesomes.

**Comment by aggelosQQ** [comment]
Bump?

**Comment by tylerhyperHD** [comment]
I mean I can create a base implementation of this rank, but I don't think I will be able to make it pick out the top 3 voters.

**Comment by aggelosQQ** [comment]
No, we will add them manually every month, we will use minecraft-mp which lists the voters.

**Comment by aggelosQQ** [comment]
Is this accepted?

**Comment by LegendIsAwesomes** [comment]
there.

**Comment by aggelosQQ** [comment]
Perfect :D

**Comment by tylerhyperHD** [comment]
I have added a listener to FHM that we can customize to do that.

**Comment by aggelosQQ** [comment]
Great.

**Comment by aggelosQQ** [comment]
@robingall2910 will you do it?
