### ISSUE TITLE
Remove the motd feature completely from TFM

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#27]
I would rather use a plugin I found and I'd love to use.

@ImmaFreedom-Dev/leaders @ImmaFreedom-Dev/member

**Comment by tylerhyperHD** [comment]
What's the plugin?

**Comment by aggelosQQ** [comment]
https://www.spigotmc.org/resources/advancedmotd.8644/

**Comment by aggelosQQ** [comment]
@tylerhyperHD, the motd I set sometimes work, sometimes it is just black.
Are you sure you removed TFM's completely?

**Comment by tylerhyperHD** [comment]
Yes, TFM's is completely turned off unless whitelist is on, you are banned, or something of that nature.

**Comment by tylerhyperHD** [comment]
Actually I figured out I made a mistake.
