### ISSUE TITLE
Config is still broken

### ISSUE THREAD

**Issue by OutOfYourMind** [ImmaFreedom-Dev/ImmaFreedomMod#29]
I can't block commands and operators can kick others.

**Comment by LegendIsAwesomes** [comment]
@OutOfYourMind when you update the config and restart/reload the server, give me all the logs (Even if there are no errors.

**Comment by tylerhyperHD** [comment]
Actually, its mainly because no one knows how to block commands correctly in the config. So its not the mods fault, its your own damn fault.
