### ISSUE TITLE
Bug with /tag

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#33]
As I see on the command, there's an auto-smite implemented that enables whenever an OP sets disallowed tags for themselves.
It is not working, everyone can set their tag to owner or admin.

**Comment by tylerhyperHD** [comment]
I am already aware of this bug.

**Comment by tylerhyperHD** [comment]
This isn't for FHM this is for IFM

**Comment by DUFCLiam** [comment]
I have done a PR #91

**Comment by RobinGall2910** [comment]
Resolved via https://github.com/ImmaFreedom-Dev/ImmaFreedomMod/pull/97.
