### ISSUE TITLE
/tagnyan admin unblocked 

### ISSUE THREAD

**Issue by LegendIsAwesomes** [ImmaFreedom-Dev/ImmaFreedomMod#4]
Will be fixed and merged soon, if anyone would like to make a PR about this, feel free. Just make sure it is accepted (Which it will be now).

**Comment by aggelosQQ** [comment]
Why will you unblock it?

**Comment by LegendIsAwesomes** [comment]
I won't. I am blocking it. ATM its unblocked by default.

**Comment by aggelosQQ** [comment]
I've already blocked them, however, I don't know if I did it correctly.
#a9fc649

**Comment by LegendIsAwesomes** [comment]
seems correct.

**Comment by LegendIsAwesomes** [comment]
Will review later, please make a PR.

**Comment by aggelosQQ** [comment]
Closed
