### ISSUE TITLE
ImmaFreedomMod is becoming FreedomHostingMod

### ISSUE THREAD

**Issue by tylerhyperHD** [ImmaFreedom-Dev/ImmaFreedomMod#41]
Currently I am creating a new mod that brings ease to the server, and this one will be made not only better than TFM, but better than any other thing. It is being created @ http://github.com/tylerhyperHD/FreedomHostingMod

This issue will close when we are completely done with the transition.

**Comment by LegendIsAwesomes** [comment]
Oi @tylerhyperHD don't forget I am going to a major part of the mod too, I plan to do a lot of commits.

**Comment by LegendIsAwesomes** [comment]
Only me and @tylerhyperhd are working on this, NOBODY ELSE. @AlphaGaming you can't either.

**Comment by LegendIsAwesomes** [comment]
@RobinGall2910 Please don't close this, it will remain open until FHM is done.
