### ISSUE TITLE
Automatic OP

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#43]
People suggested it on the server.
Since our server is not that famous rn, some people who join for the first time are not OPs and there is no one else online to op them, so I would like to see it implemented on the next update.

@ImmaFreedom-Dev/leaders @ImmaFreedom-Dev/member

**Comment by LegendIsAwesomes** [comment]
Okay, I'll just a login listener for it.

**Comment by OutOfYourMind** [comment]
I'll just make it so that multicraft ops all automatically every 2 minutes.

**Comment by aggelosQQ** [comment]
I prefer the login listenery scenario.

**Comment by LegendIsAwesomes** [comment]
Okay, will do.

**Comment by AlphaGaming** [comment]
I updated /opme so now NON_OPS can op them selfs

**Comment by aggelosQQ** [comment]
See my reply and undo it.
