### ISSUE TITLE
IF Dev

### ISSUE THREAD

**Issue by AlphaGaming** [ImmaFreedom-Dev/ImmaFreedomMod#44]
I'm a Immafreedom developer can I be added to the mod?

**Comment by LegendIsAwesomes** [comment]
Who made you a developer

**Comment by aggelosQQ** [comment]
@LegendIsAwesomes pinch did.

**Comment by aggelosQQ** [comment]
@AlphaGaming, instead of commiting  everything you change, just to avoid broking the code with unwanted stuff that have not been approved by me, just create a pull request and update it with your stuff.
