### ISSUE TITLE
Suggestion System

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#45]
Since we use a plugin which is not that good because it does not give us the ability to purge the suggestions, I came up with the idea of making our own suggestion system which will have file called suggestions.yml and this file will include all the suggestions but I want to be able to edit the messages and add some suffixes like approved, denied etc.
The commands will be too.
The first one will be /suggest <suggestion> which will take the user input and save it into the suggestions.yml on a new line like:
  - Suggestion 1
  - Suggestion 2
etc.

The second command will be /suggestions which will display all the suggestions (Page-change every 15 suggestions (for example) would be great)
They will be displayed like:
{Suggestions]: (Green)
- Suggestion 1 (Yellow)
- Suggestion 2 (Yellow)

Or we could add a special ID for each suggestion and what I will have to do is just a command, for example:
/suggestion approve <id>
Or /suggestion deny <id>
which will add suffix if approved saying approved and will delete denied or something like that.

@ImmaFreedom-Dev/member

**Comment by aggelosQQ** [comment]
@LegendIsAwesomes

**Comment by LegendIsAwesomes** [comment]
Will work on it, maybe the current ifm or the new custom one not sure.

Oft: Am I the only active developer left here?

**Comment by aggelosQQ** [comment]
Well, as it seems :P

**Comment by tylerhyperHD** [comment]
Added to the FreedomHostingMod. It will be put on the server so you can use it immediately as well.
