### ISSUE TITLE
Message to online admins only

### ISSUE THREAD

**Issue by LegendIsAwesomes** [ImmaFreedom-Dev/ImmaFreedomMod#5]
Maybe a command like /adminmsg or such alike that messages all online admins? I have accepted this at this current time, if any people object to this being added for a severe reason i will rethink my idea.

**Comment by LegendIsAwesomes** [comment]
Sorry for the spam, github was being a bit weird. This is scheduled for version 2.0, I have self-assigned this.

**Comment by LegendIsAwesomes** [comment]
Why did you close this?

**Comment by aggelosQQ** [comment]
I thought you did it xD

**Comment by LegendIsAwesomes** [comment]
@OutOfYourMind can you create this? Just want to see a commit ;)

**Comment by LegendIsAwesomes** [comment]
@outofyourmind we don't close issues unless they're of no use, this stays open.

**Comment by aggelosQQ** [comment]
Bump @ImmaFreedom-Dev/owners
