### ISSUE TITLE
Restrictions to Disguise Craft

### ISSUE THREAD

**Issue by Dusty01** [ImmaFreedom-Dev/ImmaFreedomMod#51]
It would be better to block /d p <username>. There are several ways to abuse it. I think everything can be understood easily so I wont go into it much.

**Comment by aggelosQQ** [comment]
Vouch. It should have been blocked when we firstly added it.

**Comment by samennis1** [comment]
Vouch for this, It would be a good thing to do for ImmaFreedomMod

**Comment by vladvilcu2006** [comment]
Voucheroii

**Comment by tylerhyperHD** [comment]
Imma try to redo DisguiseCraft anyways so yeah.

**Comment by DUFCLiam** [comment]
@tylerhyperHD, Want help? I can maybe help, I have a good Java decompiler, Type "jd-gui1.4.0" in google and download it.

**Comment by LegendIsAwesomes** [comment]
No @DUFCLiam, we only want developers working on this.

**Comment by DUFCLiam** [comment]
Aww, I wanna be one haha

**Comment by LegendIsAwesomes** [comment]
make lots of good PR's then

**Comment by DUFCLiam** [comment]
Okay :)

**Comment by DUFCLiam** [comment]
Wait, Legend can you help quickly.

**Comment by LegendIsAwesomes** [comment]
On what?

**Comment by DUFCLiam** [comment]
@LegendIsAwesomes, Look: http://prntscr.com/9mtt2y whats the error?

**Comment by LegendIsAwesomes** [comment]
player needs to be known as Player ( caps needed)

**Comment by DUFCLiam** [comment]
Ok, fix that in the zip then.

**Comment by DUFCLiam** [comment]
http://prntscr.com/9mtved

**Comment by LegendIsAwesomes** [comment]
It compiles, you must have something wrong.

**Comment by DUFCLiam** [comment]
Like?

**Comment by LegendIsAwesomes** [comment]
I don't know, screenshot the error when you compile and send it me on the TF forums.

**Comment by DUFCLiam** [comment]
Wait, @LegendIsAwesomes have you got skype?

**Comment by LegendIsAwesomes** [comment]
Yes, though I can't call, pm me on the TF forums about the error and I'll give you my Skype there.

**Comment by DUFCLiam** [comment]
Ok

**Comment by DUFCLiam** [comment]
@LegendIsAwesomes, Andy right

**Comment by LegendIsAwesomes** [comment]
Yes.

**Comment by tylerhyperHD** [comment]
Restrictions added.
