### ISSUE TITLE
Allow Dropping Items Except Arrows

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#52]
Please allow item dropping but keep arrows disabled.

@LegendIsAwesomes

**Comment by LegendIsAwesomes** [comment]
Okay. Will do.

**Comment by tylerhyperHD** [comment]
Actually that would lag the server out even if you just keep arrows only removed due to the various other entities that could be dropped if someone had an op item sword.

**Comment by aggelosQQ** [comment]
@tylerhyperHD then add a cooldown, like on the clearlagg, when it clears all the drops every some minutes, not instantly please.

**Comment by tylerhyperHD** [comment]
No you don't really understand the concept of a god sword - if you create a god sword with op unsafe enchantments, such as 32767 which is the highest level, a single hit of a mob would create so many mob drop entities that it would crash the server in seconds.

**Comment by aggelosQQ** [comment]
Oh yeah, you'te true.
