### ISSUE TITLE
Reasons for 'glist ban'

### ISSUE THREAD

**Issue by Dusty01** [ImmaFreedom-Dev/ImmaFreedomMod#53]
Add a 'reason' option to '/glist ban'. This can help the players understand why they were banned.

Command now:
/glist ban [user name]

Requesting command:
/glist ban [user name] [reason]

**Comment by aggelosQQ** [comment]
You mean /glist ban [ reason ] :P

**Comment by Dusty01** [comment]
I used angle brackets, which was a bad idea. I corrected it.

**Comment by OutOfYourMind** [comment]
Accepted.
