### ISSUE TITLE
Spectator

### ISSUE THREAD

**Issue by vladvilcu2006** [ImmaFreedom-Dev/ImmaFreedomMod#56]
Add /spectator, it will move you into spectator.

**Comment by FoxIshDaBest** [comment]
good idea

**Comment by vladvilcu2006** [comment]
@OutOfYourMind

**Comment by LegendIsAwesomes** [comment]
Why tag him when there is like 4 other developers to tag including me.

**Comment by vladvilcu2006** [comment]
^

**Comment by tylerhyperHD** [comment]
This has been added to FreedomHostingMod, done.
