### ISSUE TITLE
Block pet enderdragon, wither and the disguises enderdragon and wither

### ISSUE THREAD

**Issue by vladvilcu2006** [ImmaFreedom-Dev/ImmaFreedomMod#58]
Block pet enderdragon, wither and the disguises enderdragon and wither. The title says it.

**Comment by aggelosQQ** [comment]
I am pretty sure they are blocked as pets, I don't know about the desguises.

**Comment by DUFCLiam** [comment]
@aggelosQQ, I will take a look for you, what plugin is it you use?

**Comment by LegendIsAwesomes** [comment]
Theyre blocked. No need DUFCLiam.
