### ISSUE TITLE
Remove launchtorpedos

### ISSUE THREAD

**Issue by vladvilcu2006** [ImmaFreedom-Dev/ImmaFreedomMod#70]
Remove launchtorpedo, it is used for massive griefing and CANNOT be rollbacked

**Comment by DUFCLiam** [comment]
I agree with this

**Comment by tylerhyperHD** [comment]
What I did with MoveCraft is I zeroed out the explosions, I dunno if that was resolved yet.

**Comment by xItsNickHD** [comment]
It's very simple, what I think we can do is just limit it in the config. @tylerhyperHD

**Comment by aggelosQQ** [comment]
Tyler is no longer a developer @xItsNickHD.

**Comment by RobinGall2910** [comment]
There we go. This'll be removed in the config I guess.

**Comment by aggelosQQ** [comment]
I haven't seen any explosion occured. Are they disabled? @RobinGall2910

**Comment by RobinGall2910** [comment]
@aggelosQQ They are.
