### ISSUE TITLE
/tc - similar to /nc (/tagclean - similar to nickclean)

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#8]
@ImmaFreedom-Dev/owners please implement

**Comment by LegendIsAwesomes** [comment]
Will do.

**Comment by aggelosQQ** [comment]
Alright @LegendIsAwesomes thanks!

**Comment by LegendIsAwesomes** [comment]
I am doing most of my assignments about a month before the next update. (2 months), ATM the mod is finished @aggelosQQ

**Comment by aggelosQQ** [comment]
Continue coding until I get the server, @LegendIsAwesomes

**Comment by aggelosQQ** [comment]
Bump @ImmaFreedom-Dev/owners
