### ISSUE TITLE
GTFO/glist ban/unban aliases 

### ISSUE THREAD

**Issue by vladvilcu2006** [ImmaFreedom-Dev/ImmaFreedomMod#88]
Okay. I think this is useless, but anyways.

I request for someone to make GTFO and /glist ban alias to /ban. and /glist unban to /unban or /pardon

**Comment by aggelosQQ** [comment]
Our systems are fine.

**Comment by DUFCLiam** [comment]
I think this would be a bad idea anyways; It was be mistakenly used.
