### ISSUE TITLE
Youtuber Rank

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#9]
Can we add a custom title like Owner, executive or sys-admin called Youtuber?
On /list it will show 
&7[&4You&4Tuber&7] 
It will have some commands like /recording (with actual countdown)

I want to be able to make people youtubers using config.yml.
Like, for example:
owners:
 - aggelosQQ

something like:

youtubers:
  - aggelosQQ

@ImmaFreedom-Dev/owners

**Comment by LegendIsAwesomes** [comment]
Decent idea. @OutOfYourMind what do you think?

**Comment by aggelosQQ** [comment]
uhh, we will implement this xD

**Comment by aggelosQQ** [comment]
@LegendIsAwesomes so?? When are you going to add this?

**Comment by LegendIsAwesomes** [comment]
I am, just wont be merged anytime soon.

**Comment by LegendIsAwesomes** [comment]
I don't think this would work out, Anyone can use /tag to be a youtuber, It would have to go through hard code (normally), meaning everytime someone wanted to be a youtuber i'd have to update the mod.

**Comment by aggelosQQ** [comment]
@LegendIsAwesomes that's why I asked to do it like the owners on config.yml but instead of owners, youtubers.

E.g: 
youtubers:
 - aggelosQQ

**Comment by LegendIsAwesomes** [comment]
That would be very, very hard to implement.

**Comment by OutOfYourMind** [comment]
I cannot add this, I apologize. Maybe in the future.
