### ISSUE TITLE
Command Suggestion: /admin

### ISSUE THREAD

**Issue by DUFCLiam** [ImmaFreedom-Dev/ImmaFreedomMod#94]
# Command Suggestion: /admin
It can have more features like

/admin [doom | remove | add | suspend | etc]

**Comment by aggelosQQ** [comment]
Umm??

**Comment by AvalancheYT** [comment]
No thanks.

**Comment by DUFCLiam** [comment]
@aggelosQQ @AvalancheYT Fixed it was in < >'s

**Comment by aggelosQQ** [comment]
No need.
