### ISSUE TITLE
spectator

### ISSUE THREAD

**Issue by vladvilcu2006** [ImmaFreedom-Dev/ImmaFreedomMod#99]
This is not a duplicated issue, As FreedomHostingMod was removed, we need to add /spectator again...

**Comment by DUFCLiam** [comment]
Agreed, I will create a PR for some of your new PRs :)

**Comment by AvalancheYT** [comment]
Shouldn't the issues be accepted before creating a pull request.

**Comment by aggelosQQ** [comment]
We won't have this command.
